version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: sot_flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: sot_flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: QE93rQTfSBAxXR8u
      MONGODB_HOSTNAME: sot_mongodb
    volumes:
      - appdata:/home/Senate/SenateBot/api/sot/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

